interface RefractionDetailModel {
  id: number;
  refraction: number;
  patient: null | object;
  hb_rx_right_dist: number | null;
  hb_rx_left_dist: number | null;
  hb_rx_right_near: number | null;
  hb_rx_left_near: number | null;
  auto_ref_right: number | null;
  auto_ref_left: number | null;
  ntc_left: number | null;
  ntc_right: number | null;
  right_eye_dist_sph: number | null;
  right_eye_dist_cyl: number | null;
  right_eye_dist_axis: number | null;
  right_eye_near_sph: number | null;
  left_eye_dist_sph: number | null;
  left_eye_dist_cyl: number | null;
  left_eye_dist_axis: number | null;
  left_eye_near_sph: number | null;
  remark: string;
  note: string;
  name: string;
  nic: string;
  phone_number: string;
  address: string;
  dob: string;
  discount: number;
  cash: number;
  card: number;
  is_manual: boolean;
}
export type { RefractionDetailModel };
