import * as Yup from "yup";

export const factoryInvoiceSchema = Yup.object().shape({
  sales_staff_code: Yup.string(),
  hb_rx_right_dist: Yup.string(),
  hb_rx_left_dist: Yup.string(),
  hb_rx_right_near: Yup.string(),
  hb_rx_left_near: Yup.string(),
  auto_ref_right: Yup.string(),
  auto_ref_left: Yup.string(),
  right_eye_dist_sph: Yup.string(),
  right_eye_dist_cyl: Yup.string(),
  right_eye_dist_axis: Yup.string(),
  right_eye_near_sph: Yup.string(),
  left_eye_dist_sph: Yup.string(),
  left_eye_dist_cyl: Yup.string(),
  left_eye_dist_axis: Yup.string(),
  left_eye_near_sph: Yup.string(),
  remark: Yup.string(),
  name: Yup.string(),
  nic: Yup.string(),
  phone_number: Yup.string(),
  address: Yup.string(),
  dob: Yup.string(),
  discount: Yup.number().required("discount is required").min(0),
  cash: Yup.number().required("payment Amount is required").min(0),
  card: Yup.number().required("payment Amount is required").min(0),
});
